spring:
  application:
    name: MainMicroServiceBtcIp

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

external:
  service:
    url: http://localhost:8081/request

logging:
  level:
    root: info
    org.springframework.web: DEBUG
    org.springframework.security: WARN